# Notebook 2: Cleaning Data

Real data is messy. Let's learn how to clean it!

In [1]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_csv('../data/sales.csv')
df

         date   product  quantity  price region
0  2024-01-15    Laptop         2   1000  North
1  2024-01-16     Mouse         5     25  South
2  2024-01-17  Keyboard         3     75   East
3  2024-01-18   Monitor         1    400   West
4  2024-01-19    Laptop         1   1000  North
5  2024-01-20     Mouse        10     25  South
6  2024-01-21  Keyboard         2     75   East
7  2024-01-22   Monitor         2    400   West

## 1. Find Missing Values

In [2]:
# Check for missing values
df.isnull().sum()

date        0
product     0
quantity    0
price       0
region      0
dtype: int64

## 2. Handle Missing Values

In [3]:
# Option 1: Drop rows with missing values
df_clean = df.dropna()
print(f"Original: {len(df)} rows")
print(f"After dropping: {len(df_clean)} rows")

Original: 8 rows
After dropping: 8 rows

In [4]:
# Option 2: Fill missing values
df_filled = df.fillna(0)  # Fill with 0
df_filled

         date   product  quantity  price region
0  2024-01-15    Laptop         2   1000  North
1  2024-01-16     Mouse         5     25  South
2  2024-01-17  Keyboard         3     75   East
3  2024-01-18   Monitor         1    400   West
4  2024-01-19    Laptop         1   1000  North
5  2024-01-20     Mouse        10     25  South
6  2024-01-21  Keyboard         2     75   East
7  2024-01-22   Monitor         2    400   West

## 3. Find Duplicates

In [5]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [6]:
# Remove duplicates
df_unique = df.drop_duplicates()
print(f"Rows after removing duplicates: {len(df_unique)}")

Rows after removing duplicates: 8

## 4. Fix Data Types

In [7]:
# Check data types
df.dtypes

date          str
product       str
quantity    int64
price       int64
region        str
dtype: object

In [8]:
# Convert date column
df['date'] = pd.to_datetime(df['date'])
df.dtypes

date        datetime64[us]
product                str
quantity             int64
price                int64
region                 str
dtype: object

## 5. Clean Text Data

In [9]:
# Make text lowercase
df['product'] = df['product'].str.lower()
df

        date   product  quantity  price region
0 2024-01-15    laptop         2   1000  North
1 2024-01-16     mouse         5     25  South
2 2024-01-17  keyboard         3     75   East
3 2024-01-18   monitor         1    400   West
4 2024-01-19    laptop         1   1000  North
5 2024-01-20     mouse        10     25  South
6 2024-01-21  keyboard         2     75   East
7 2024-01-22   monitor         2    400   West

In [10]:
# Remove spaces
df['product'] = df['product'].str.strip()
df

        date   product  quantity  price region
0 2024-01-15    laptop         2   1000  North
1 2024-01-16     mouse         5     25  South
2 2024-01-17  keyboard         3     75   East
3 2024-01-18   monitor         1    400   West
4 2024-01-19    laptop         1   1000  North
5 2024-01-20     mouse        10     25  South
6 2024-01-21  keyboard         2     75   East
7 2024-01-22   monitor         2    400   West

## 🎯 Practice Exercises

1. Add some missing values to your data and practice filling them
2. Create duplicate rows and remove them
3. Clean the 'region' column (make all uppercase)
4. Calculate total sales (quantity × price) for each row