In [1]:
import pandas as pd
# 1. Find a messy CSV (or use the UC Berkeley baby names dataset ).
df = pd.read_csv('../data/NationalNames.csv')
df.head(5)

   Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746

In [2]:
# 2. Convert all string columns to title case.
df['Name'] = df['Name'].str.title()
df['Gender'] = df['Gender'].str.title()

# or

# Select all columns with object/string data types and apply title case
string_cols = df.select_dtypes(include=['object', 'string']).columns
df[string_cols] = df[string_cols].astype(str).apply(lambda x: x.str.title())

In [7]:
# 3. Create a new column extracting the first 3 letters of each name.
df['Name_Id'] = df['Name'].str.slice(0, 3)
# or
# df['Name'].str[:3]
df

              Id       Name  Year Gender  Count Name_Id
0              1       Mary  1880      F   7065     Mar
1              2       Anna  1880      F   2604     Ann
2              3       Emma  1880      F   2003     Emm
3              4  Elizabeth  1880      F   1939     Eli
4              5     Minnie  1880      F   1746     Min
...          ...        ...   ...    ...    ...     ...
1825428  1825429     Zykeem  2014      M      5     Zyk
1825429  1825430     Zymeer  2014      M      5     Zym
1825430  1825431    Zymiere  2014      M      5     Zym
1825431  1825432      Zyran  2014      M      5     Zyr
1825432  1825433      Zyrin  2014      M      5     Zyr

[1825433 rows x 6 columns]

In [10]:
# 4. Identify columns with missing data. Impute numeric columns with median, categorical columns with mode.
df.isna().sum()

# Everything is clean I don't have to do anything.

Id         0
Name       0
Year       0
Gender     0
Count      0
Name_Id    0
dtype: int64

In [1]:
# 5. Challenge: Use pd.to_numeric(..., errors='coerce') to convert a messy column to numbers, coercing errors to NaN.

# I have to do this later.